import { useGameStore } from "../../store/game-store";
import styles from "./lobby.module.css";

export function Lobby() {
  const lobby = useGameStore((state) => state.lobbyState); const roomCode = useGameStore((state) => state.roomCode); const playerId = useGameStore((state) => state.playerId); const isHost = useGameStore((state) => state.isHost); const connected = useGameStore((state) => state.connected); const setReady = useGameStore((state) => state.setReady); const start = useGameStore((state) => state.startMultiplayerGame); const leave = useGameStore((state) => state.resetGame);
  if (!lobby || !roomCode) return null;
  const me = lobby.players.find((player) => player.id === playerId); const allReady = lobby.players.length >= 2 && lobby.players.every((player) => player.ready); const shareUrl = `${window.location.origin}/?room=${roomCode}`;
  const copy = async () => { try { await navigator.clipboard.writeText(shareUrl); } catch { /* clipboard unavailable */ } };
  return <div className={styles.lobby}><div className={styles.content}><div className={styles.header}>THE DOT GAME <span style={{ fontSize: "0.5em", opacity: 0.65 }}>{isHost ? "HOST" : "GUEST"}</span></div><div className={styles.matchmaking}><div className={styles.status}>{connected ? `${lobby.players.length}/${lobby.settings.maxPlayers} PLAYERS` : "RECONNECTING…"}</div><div style={{ display: "grid", gap: 10, marginTop: 24 }}>{lobby.players.map((player) => <div key={player.id} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", border: "2px solid var(--ink)", padding: "0.8rem", background: player.id === playerId ? "var(--ink)" : "transparent", color: player.id === playerId ? "var(--paper)" : "inherit" }}><span>{player.name}{player.id === lobby.hostId ? " · HOST" : ""}</span><span>{!player.connected ? "OFFLINE" : player.ready ? "READY" : "NOT READY"}</span></div>)}{lobby.players.length < lobby.settings.maxPlayers && <div style={{ padding: "1rem", border: "2px dashed var(--ink)", opacity: 0.6, textAlign: "center" }}>Share the code to invite more players</div>}</div><div className={styles.divider} /><div className={styles.details}><div><div className={styles.detailLabel}>BOARD</div><div>{lobby.settings.board.width} × {lobby.settings.board.height}</div></div><div style={{ textAlign: "right" }}><div className={styles.detailLabel}>TIMER</div><div>{lobby.settings.timerMode ? `${lobby.settings.timerMode}s` : "OFF"}</div></div></div></div><div className={styles.codeSection}><div className={styles.codeLabel}>INVITE CODE</div><button className={styles.code} onClick={copy} aria-label="Copy invite code">{roomCode}</button><button onClick={copy} style={{ marginTop: 8, textDecoration: "underline", fontSize: 12 }}>Copy invite link</button></div><div className={styles.actions}>{me && <button className={styles.startBtn} onClick={() => setReady(!me.ready)} disabled={!connected}>{me.ready ? "Mark not ready" : "Ready up"}</button>}{isHost && <button className={styles.startBtn} onClick={start} disabled={!allReady || !connected}>{allReady ? "Start match" : "Waiting for ready players"}</button>}{!isHost && <div style={{ textAlign: "center", opacity: 0.7 }}>{allReady ? "Waiting for host to start" : "Ready up when you are set"}</div>}<button className={styles.cancelBtn} onClick={leave}>Leave room</button></div></div></div>;
}
